dist: trusty
sudo: required
language: python

services:
- docker

python:
- 2.7
- 3.4
- 3.5
- 3.5-dev
- 3.6
- 3.6-dev
- 3.7-dev
- nightly
- pypy-5.4.1

node_js:
- 5

env:
- SINGVER=3.4.2  # the version of docker2singularity used below should match this one

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq python dh-autoreconf squashfs-tools build-essential libarchive-dev
- npm install jsonlint -g 
- docker build -t boutiques/example1:test ./tools/python/boutiques/schema/examples/example1
- docker run -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}:/output --privileged -t --rm singularityware/docker2singularity:v3.4.0 boutiques/example1:test
- IMGNAME=$(ls $HOME/boutiques_example1_test*.simg)
- go env
- sudo rm -r /home/travis/go
- sudo echo /etc/profile
- sudo echo /$HOME/.profile
- export GOVERSION=1.12 OS=linux ARCH=amd64
- wget https://dl.google.com/go/go$GOVERSION.$OS-$ARCH.tar.gz
- sudo tar -C /usr/local -xzvf go$GOVERSION.$OS-$ARCH.tar.gz
- echo 'export GOPATH=${HOME}/go' >> ~/.bashrc
- echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc
- source ~/.bashrc
- sudo bash -c 'echo Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin" > /etc/sudoers.d/0_config'
- sudo visudo -cf /etc/sudoers.d/0_config
- sudo go env
- wget https://github.com/sylabs/singularity/releases/download/v$SINGVER/singularity-$SINGVER.tar.gz
- tar xvf singularity-$SINGVER.tar.gz
- cd singularity
- sudo -E ./mconfig
- make -C ./builddir
- sudo make -C ./builddir install
- singularity --version
- cat /etc/singularity/singularity.conf
- cd ${TRAVIS_BUILD_DIR}/tools/python/
- mv ${IMGNAME} ./boutiques-example1-test.simg

install:
- pip install --upgrade setuptools
- pip install "jsonschema>=2.6.0,<3.0.0"
- pip install pytest pytest-runner pycodestyle coveralls
- pip install .
- pip freeze

script:
- pycodestyle --max-line-length=80 boutiques/*.py boutiques/tests/*.py
- jsonlint -q boutiques/schema/descriptor.schema.json
- coverage run --source boutiques setup.py pytest
- coverage report -m

after_success:
- coveralls

deploy:
